services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.production
    ports:
      - "8080:80"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=crm_db
      - DB_USER=crm_user
      - DB_PASSWORD=crm_password
      - JWT_SECRET=your-super-secret-jwt-key-change-this
      - JWT_EXPIRATION=86400
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm_db
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crm_password
    ports:
      - "3306:3306"
    volumes:
      - crm_shared_db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  crm_shared_db_data:
    external: true